# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55b47935231099af5ebb3d4c13bd3f5cf9cdc7ace8f75ecd3db6126725e8ef3effa9df2fbe4f57e86536c20e55409cdcff47386a843ec2312137770516445ecf

test:
  secret_key_base: 78a7008ac88df02246ad9b4fd74e577a99a2a9f8823dd29b6d5c6a245a83ae36fe9bca4178c043833388c377f4bd363aae0ab9c6b4a14e050f5375276cb5aaa8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
